version: "3.7"

services:
  database_growth:
    image: postgres
    container_name: database_growth
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=growth
      - POSTGRES_DB=growth
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/data/postgres
    restart: always
  app:
    build: .
    container_name: growth-api
    ports: 
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_growth
    depends_on: 
      - database_growth
  
volumes:
  pgdata:
    driver: local